// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using website.Data;

namespace website.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20180318041052_foreignkey")]
    partial class foreignkey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("website.Models.DonationModel", b =>
                {
                    b.Property<int>("DonationId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<int>("IdeaId");

                    b.HasKey("DonationId");

                    b.HasIndex("IdeaId");

                    b.ToTable("Donation");
                });

            modelBuilder.Entity("website.Models.IdeaModel", b =>
                {
                    b.Property<int>("IdeaId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("FundGoal");

                    b.Property<string>("ImagePath")
                        .IsRequired();

                    b.Property<string>("ProductContent")
                        .IsRequired();

                    b.Property<string>("ProductName")
                        .IsRequired();

                    b.HasKey("IdeaId");

                    b.ToTable("Idea");
                });

            modelBuilder.Entity("website.Models.DonationModel", b =>
                {
                    b.HasOne("website.Models.IdeaModel", "Idea")
                        .WithMany("Donations")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
